version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongo-container
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: user
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
